import 'dotenv/config'
import { db } from './index'
import { decks, words } from './schema'

const HSK1_DECKS = [
  { name: 'Greetings', description: 'Greetings, farewells, and polite expressions', level: 'HSK1' },
  { name: 'Pronouns', description: 'Personal pronouns and question words', level: 'HSK1' },
  { name: 'Numbers', description: 'Numbers, measure words, and quantities', level: 'HSK1' },
  { name: 'Time', description: 'Time expressions, days, and periods of the day', level: 'HSK1' },
  { name: 'Family', description: 'Family members and relationships', level: 'HSK1' },
  { name: 'People', description: 'People, professions, and social terms', level: 'HSK1' },
  { name: 'Nouns · Food', description: 'Food and meals', level: 'HSK1' },
  { name: 'Nouns · Drinks', description: 'Drinks and beverages', level: 'HSK1' },
  { name: 'Places', description: 'Places, locations, and buildings', level: 'HSK1' },
  { name: 'Transportation', description: 'Transport and travel', level: 'HSK1' },
  { name: 'Colors', description: 'Colors', level: 'HSK1' },
  { name: 'Clothing', description: 'Clothing and accessories', level: 'HSK1' },
  { name: 'Body & Health', description: 'Body parts and health', level: 'HSK1' },
  { name: 'Weather & Nature', description: 'Weather, nature, and environment', level: 'HSK1' },
  { name: 'Home & Objects', description: 'Home, rooms, and common objects', level: 'HSK1' },
  { name: 'School', description: 'School, study, and learning', level: 'HSK1' },
  { name: 'Work & Shopping', description: 'Work, shopping, and money', level: 'HSK1' },
  { name: 'Verbs · Core', description: 'Essential action verbs', level: 'HSK1' },
  { name: 'Verbs · Daily Life', description: 'Everyday activity verbs', level: 'HSK1' },
  { name: 'Verbs · Activities', description: 'Sports, hobbies, and leisure', level: 'HSK1' },
  { name: 'Adjectives', description: 'Describing words and states', level: 'HSK1' },
  { name: 'Adverbs & Particles', description: 'Adverbs, conjunctions, and particles', level: 'HSK1' },
]

const HSK1_WORDS = [
  // ── Greetings ────────────────────────────────────────────
  { simplified: '你好', traditional: '你好', pinyin: 'nǐ hǎo', tones: [3, 3], meaning: 'hello', deck: 'Greetings' },
  { simplified: '谢谢', traditional: '謝謝', pinyin: 'xiè xie', tones: [4, 0], meaning: 'thank you', deck: 'Greetings' },
  { simplified: '对不起', traditional: '對不起', pinyin: 'duì bu qǐ', tones: [4, 0, 3], meaning: 'sorry', deck: 'Greetings' },
  { simplified: '没关系', traditional: '沒關係', pinyin: 'méi guān xi', tones: [2, 1, 0], meaning: "it's okay / never mind", deck: 'Greetings' },
  { simplified: '不客气', traditional: '不客氣', pinyin: 'bú kè qi', tones: [2, 4, 0], meaning: "you're welcome", deck: 'Greetings' },
  { simplified: '再见', traditional: '再見', pinyin: 'zài jiàn', tones: [4, 4], meaning: 'goodbye', deck: 'Greetings' },
  { simplified: '请', traditional: '請', pinyin: 'qǐng', tones: [3], meaning: 'please / to invite', deck: 'Greetings' },
  { simplified: '您好', traditional: '您好', pinyin: 'nín hǎo', tones: [2, 3], meaning: 'hello (formal)', deck: 'Greetings' },

  // ── Pronouns ─────────────────────────────────────────────
  { simplified: '我', traditional: '我', pinyin: 'wǒ', tones: [3], meaning: 'I / me', deck: 'Pronouns' },
  { simplified: '你', traditional: '你', pinyin: 'nǐ', tones: [3], meaning: 'you', deck: 'Pronouns' },
  { simplified: '您', traditional: '您', pinyin: 'nín', tones: [2], meaning: 'you (formal)', deck: 'Pronouns' },
  { simplified: '他', traditional: '他', pinyin: 'tā', tones: [1], meaning: 'he / him', deck: 'Pronouns' },
  { simplified: '她', traditional: '她', pinyin: 'tā', tones: [1], meaning: 'she / her', deck: 'Pronouns' },
  { simplified: '它', traditional: '它', pinyin: 'tā', tones: [1], meaning: 'it', deck: 'Pronouns' },
  { simplified: '我们', traditional: '我們', pinyin: 'wǒ men', tones: [3, 0], meaning: 'we / us', deck: 'Pronouns' },
  { simplified: '你们', traditional: '你們', pinyin: 'nǐ men', tones: [3, 0], meaning: 'you (plural)', deck: 'Pronouns' },
  { simplified: '他们', traditional: '他們', pinyin: 'tā men', tones: [1, 0], meaning: 'they / them', deck: 'Pronouns' },
  { simplified: '这', traditional: '這', pinyin: 'zhè', tones: [4], meaning: 'this', deck: 'Pronouns' },
  { simplified: '那', traditional: '那', pinyin: 'nà', tones: [4], meaning: 'that', deck: 'Pronouns' },
  { simplified: '这个', traditional: '這個', pinyin: 'zhè ge', tones: [4, 0], meaning: 'this one', deck: 'Pronouns' },
  { simplified: '那个', traditional: '那個', pinyin: 'nà ge', tones: [4, 0], meaning: 'that one', deck: 'Pronouns' },
  { simplified: '这里', traditional: '這裡', pinyin: 'zhè lǐ', tones: [4, 3], meaning: 'here', deck: 'Pronouns' },
  { simplified: '那里', traditional: '那裡', pinyin: 'nà lǐ', tones: [4, 3], meaning: 'there', deck: 'Pronouns' },
  { simplified: '哪', traditional: '哪', pinyin: 'nǎ', tones: [3], meaning: 'which', deck: 'Pronouns' },
  { simplified: '哪里', traditional: '哪裡', pinyin: 'nǎ lǐ', tones: [3, 3], meaning: 'where', deck: 'Pronouns' },
  { simplified: '谁', traditional: '誰', pinyin: 'shéi', tones: [2], meaning: 'who', deck: 'Pronouns' },
  { simplified: '什么', traditional: '什麼', pinyin: 'shén me', tones: [2, 0], meaning: 'what', deck: 'Pronouns' },
  { simplified: '多少', traditional: '多少', pinyin: 'duō shao', tones: [1, 0], meaning: 'how many / how much', deck: 'Pronouns' },
  { simplified: '几', traditional: '幾', pinyin: 'jǐ', tones: [3], meaning: 'how many (small number)', deck: 'Pronouns' },
  { simplified: '怎么', traditional: '怎麼', pinyin: 'zěn me', tones: [3, 0], meaning: 'how / why', deck: 'Pronouns' },
  { simplified: '为什么', traditional: '為什麼', pinyin: 'wèi shén me', tones: [4, 2, 0], meaning: 'why', deck: 'Pronouns' },

  // ── Numbers ──────────────────────────────────────────────
  { simplified: '零', traditional: '零', pinyin: 'líng', tones: [2], meaning: 'zero', deck: 'Numbers' },
  { simplified: '一', traditional: '一', pinyin: 'yī', tones: [1], meaning: 'one', deck: 'Numbers' },
  { simplified: '二', traditional: '二', pinyin: 'èr', tones: [4], meaning: 'two', deck: 'Numbers' },
  { simplified: '三', traditional: '三', pinyin: 'sān', tones: [1], meaning: 'three', deck: 'Numbers' },
  { simplified: '四', traditional: '四', pinyin: 'sì', tones: [4], meaning: 'four', deck: 'Numbers' },
  { simplified: '五', traditional: '五', pinyin: 'wǔ', tones: [3], meaning: 'five', deck: 'Numbers' },
  { simplified: '六', traditional: '六', pinyin: 'liù', tones: [4], meaning: 'six', deck: 'Numbers' },
  { simplified: '七', traditional: '七', pinyin: 'qī', tones: [1], meaning: 'seven', deck: 'Numbers' },
  { simplified: '八', traditional: '八', pinyin: 'bā', tones: [1], meaning: 'eight', deck: 'Numbers' },
  { simplified: '九', traditional: '九', pinyin: 'jiǔ', tones: [3], meaning: 'nine', deck: 'Numbers' },
  { simplified: '十', traditional: '十', pinyin: 'shí', tones: [2], meaning: 'ten', deck: 'Numbers' },
  { simplified: '百', traditional: '百', pinyin: 'bǎi', tones: [3], meaning: 'hundred', deck: 'Numbers' },
  { simplified: '千', traditional: '千', pinyin: 'qiān', tones: [1], meaning: 'thousand', deck: 'Numbers' },
  { simplified: '万', traditional: '萬', pinyin: 'wàn', tones: [4], meaning: 'ten thousand', deck: 'Numbers' },
  { simplified: '两', traditional: '兩', pinyin: 'liǎng', tones: [3], meaning: 'two / both', deck: 'Numbers' },
  { simplified: '半', traditional: '半', pinyin: 'bàn', tones: [4], meaning: 'half', deck: 'Numbers' },
  { simplified: '第', traditional: '第', pinyin: 'dì', tones: [4], meaning: 'ordinal prefix (1st, 2nd…)', deck: 'Numbers' },
  { simplified: '个', traditional: '個', pinyin: 'gè', tones: [4], meaning: '(general measure word)', deck: 'Numbers' },
  { simplified: '本', traditional: '本', pinyin: 'běn', tones: [3], meaning: '(MW: books)', deck: 'Numbers' },
  { simplified: '张', traditional: '張', pinyin: 'zhāng', tones: [1], meaning: '(MW: flat objects)', deck: 'Numbers' },
  { simplified: '条', traditional: '條', pinyin: 'tiáo', tones: [2], meaning: '(MW: long objects)', deck: 'Numbers' },
  { simplified: '件', traditional: '件', pinyin: 'jiàn', tones: [4], meaning: '(MW: clothing / matters)', deck: 'Numbers' },
  { simplified: '次', traditional: '次', pinyin: 'cì', tones: [4], meaning: 'time / occurrence', deck: 'Numbers' },
  { simplified: '岁', traditional: '歲', pinyin: 'suì', tones: [4], meaning: 'years old', deck: 'Numbers' },
  { simplified: '些', traditional: '些', pinyin: 'xiē', tones: [1], meaning: 'some / a few', deck: 'Numbers' },

  // ── Time ─────────────────────────────────────────────────
  { simplified: '年', traditional: '年', pinyin: 'nián', tones: [2], meaning: 'year', deck: 'Time' },
  { simplified: '月', traditional: '月', pinyin: 'yuè', tones: [4], meaning: 'month', deck: 'Time' },
  { simplified: '日', traditional: '日', pinyin: 'rì', tones: [4], meaning: 'day / date', deck: 'Time' },
  { simplified: '号', traditional: '號', pinyin: 'hào', tones: [4], meaning: 'date / number', deck: 'Time' },
  { simplified: '星期', traditional: '星期', pinyin: 'xīng qī', tones: [1, 1], meaning: 'week', deck: 'Time' },
  { simplified: '今天', traditional: '今天', pinyin: 'jīn tiān', tones: [1, 1], meaning: 'today', deck: 'Time' },
  { simplified: '明天', traditional: '明天', pinyin: 'míng tiān', tones: [2, 1], meaning: 'tomorrow', deck: 'Time' },
  { simplified: '昨天', traditional: '昨天', pinyin: 'zuó tiān', tones: [2, 1], meaning: 'yesterday', deck: 'Time' },
  { simplified: '现在', traditional: '現在', pinyin: 'xiàn zài', tones: [4, 4], meaning: 'now', deck: 'Time' },
  { simplified: '时候', traditional: '時候', pinyin: 'shí hòu', tones: [2, 4], meaning: 'time / moment', deck: 'Time' },
  { simplified: '时间', traditional: '時間', pinyin: 'shí jiān', tones: [2, 1], meaning: 'time (duration)', deck: 'Time' },
  { simplified: '上午', traditional: '上午', pinyin: 'shàng wǔ', tones: [4, 3], meaning: 'morning (AM)', deck: 'Time' },
  { simplified: '下午', traditional: '下午', pinyin: 'xià wǔ', tones: [4, 3], meaning: 'afternoon (PM)', deck: 'Time' },
  { simplified: '晚上', traditional: '晚上', pinyin: 'wǎn shàng', tones: [3, 4], meaning: 'evening / night', deck: 'Time' },
  { simplified: '早上', traditional: '早上', pinyin: 'zǎo shàng', tones: [3, 4], meaning: 'early morning', deck: 'Time' },
  { simplified: '中午', traditional: '中午', pinyin: 'zhōng wǔ', tones: [1, 3], meaning: 'noon / midday', deck: 'Time' },
  { simplified: '以后', traditional: '以後', pinyin: 'yǐ hòu', tones: [3, 4], meaning: 'after / later', deck: 'Time' },
  { simplified: '以前', traditional: '以前', pinyin: 'yǐ qián', tones: [3, 2], meaning: 'before / ago', deck: 'Time' },
  { simplified: '小时', traditional: '小時', pinyin: 'xiǎo shí', tones: [3, 2], meaning: 'hour', deck: 'Time' },
  { simplified: '分钟', traditional: '分鐘', pinyin: 'fēn zhōng', tones: [1, 1], meaning: 'minute', deck: 'Time' },
  { simplified: '早', traditional: '早', pinyin: 'zǎo', tones: [3], meaning: 'early', deck: 'Time' },
  { simplified: '天', traditional: '天', pinyin: 'tiān', tones: [1], meaning: 'day / sky', deck: 'Time' },

  // ── Family ───────────────────────────────────────────────
  { simplified: '爸爸', traditional: '爸爸', pinyin: 'bà ba', tones: [4, 0], meaning: 'father / dad', deck: 'Family' },
  { simplified: '妈妈', traditional: '媽媽', pinyin: 'mā ma', tones: [1, 0], meaning: 'mother / mom', deck: 'Family' },
  { simplified: '哥哥', traditional: '哥哥', pinyin: 'gē ge', tones: [1, 0], meaning: 'older brother', deck: 'Family' },
  { simplified: '姐姐', traditional: '姐姐', pinyin: 'jiě jie', tones: [3, 0], meaning: 'older sister', deck: 'Family' },
  { simplified: '弟弟', traditional: '弟弟', pinyin: 'dì di', tones: [4, 0], meaning: 'younger brother', deck: 'Family' },
  { simplified: '妹妹', traditional: '妹妹', pinyin: 'mèi mei', tones: [4, 0], meaning: 'younger sister', deck: 'Family' },
  { simplified: '儿子', traditional: '兒子', pinyin: 'ér zi', tones: [2, 0], meaning: 'son', deck: 'Family' },
  { simplified: '女儿', traditional: '女兒', pinyin: 'nǚ ér', tones: [3, 2], meaning: 'daughter', deck: 'Family' },
  { simplified: '爷爷', traditional: '爺爺', pinyin: 'yé ye', tones: [2, 0], meaning: 'paternal grandfather', deck: 'Family' },
  { simplified: '奶奶', traditional: '奶奶', pinyin: 'nǎi nai', tones: [3, 0], meaning: 'paternal grandmother', deck: 'Family' },
  { simplified: '丈夫', traditional: '丈夫', pinyin: 'zhàng fu', tones: [4, 0], meaning: 'husband', deck: 'Family' },
  { simplified: '妻子', traditional: '妻子', pinyin: 'qī zi', tones: [1, 0], meaning: 'wife', deck: 'Family' },
  { simplified: '家', traditional: '家', pinyin: 'jiā', tones: [1], meaning: 'home / family', deck: 'Family' },

  // ── People ───────────────────────────────────────────────
  { simplified: '人', traditional: '人', pinyin: 'rén', tones: [2], meaning: 'person / people', deck: 'People' },
  { simplified: '男人', traditional: '男人', pinyin: 'nán rén', tones: [2, 2], meaning: 'man', deck: 'People' },
  { simplified: '女人', traditional: '女人', pinyin: 'nǚ rén', tones: [3, 2], meaning: 'woman', deck: 'People' },
  { simplified: '孩子', traditional: '孩子', pinyin: 'hái zi', tones: [2, 0], meaning: 'child', deck: 'People' },
  { simplified: '男孩', traditional: '男孩', pinyin: 'nán hái', tones: [2, 2], meaning: 'boy', deck: 'People' },
  { simplified: '女孩', traditional: '女孩', pinyin: 'nǚ hái', tones: [3, 2], meaning: 'girl', deck: 'People' },
  { simplified: '朋友', traditional: '朋友', pinyin: 'péng you', tones: [2, 0], meaning: 'friend', deck: 'People' },
  { simplified: '同学', traditional: '同學', pinyin: 'tóng xué', tones: [2, 2], meaning: 'classmate', deck: 'People' },
  { simplified: '老师', traditional: '老師', pinyin: 'lǎo shī', tones: [3, 1], meaning: 'teacher', deck: 'People' },
  { simplified: '学生', traditional: '學生', pinyin: 'xué shēng', tones: [2, 1], meaning: 'student', deck: 'People' },
  { simplified: '医生', traditional: '醫生', pinyin: 'yī shēng', tones: [1, 1], meaning: 'doctor', deck: 'People' },
  { simplified: '服务员', traditional: '服務員', pinyin: 'fú wù yuán', tones: [2, 4, 2], meaning: 'waiter / service staff', deck: 'People' },

  // ── Nouns · Food ─────────────────────────────────────────
  { simplified: '米饭', traditional: '米飯', pinyin: 'mǐ fàn', tones: [3, 4], meaning: 'rice (cooked)', deck: 'Nouns · Food' },
  { simplified: '面条', traditional: '麵條', pinyin: 'miàn tiáo', tones: [4, 2], meaning: 'noodles', deck: 'Nouns · Food' },
  { simplified: '面包', traditional: '麵包', pinyin: 'miàn bāo', tones: [4, 1], meaning: 'bread', deck: 'Nouns · Food' },
  { simplified: '饺子', traditional: '餃子', pinyin: 'jiǎo zi', tones: [3, 0], meaning: 'dumplings', deck: 'Nouns · Food' },
  { simplified: '苹果', traditional: '蘋果', pinyin: 'píng guǒ', tones: [2, 3], meaning: 'apple', deck: 'Nouns · Food' },
  { simplified: '梨', traditional: '梨', pinyin: 'lí', tones: [2], meaning: 'pear', deck: 'Nouns · Food' },
  { simplified: '香蕉', traditional: '香蕉', pinyin: 'xiāng jiāo', tones: [1, 1], meaning: 'banana', deck: 'Nouns · Food' },
  { simplified: '西瓜', traditional: '西瓜', pinyin: 'xī guā', tones: [1, 1], meaning: 'watermelon', deck: 'Nouns · Food' },
  { simplified: '菜', traditional: '菜', pinyin: 'cài', tones: [4], meaning: 'vegetable / dish', deck: 'Nouns · Food' },
  { simplified: '肉', traditional: '肉', pinyin: 'ròu', tones: [4], meaning: 'meat', deck: 'Nouns · Food' },
  { simplified: '鱼', traditional: '魚', pinyin: 'yú', tones: [2], meaning: 'fish', deck: 'Nouns · Food' },
  { simplified: '鸡蛋', traditional: '雞蛋', pinyin: 'jī dàn', tones: [1, 4], meaning: 'egg', deck: 'Nouns · Food' },
  { simplified: '饭', traditional: '飯', pinyin: 'fàn', tones: [4], meaning: 'cooked rice / meal', deck: 'Nouns · Food' },
  { simplified: '早饭', traditional: '早飯', pinyin: 'zǎo fàn', tones: [3, 4], meaning: 'breakfast', deck: 'Nouns · Food' },
  { simplified: '午饭', traditional: '午飯', pinyin: 'wǔ fàn', tones: [3, 4], meaning: 'lunch', deck: 'Nouns · Food' },
  { simplified: '晚饭', traditional: '晚飯', pinyin: 'wǎn fàn', tones: [3, 4], meaning: 'dinner', deck: 'Nouns · Food' },
  { simplified: '水果', traditional: '水果', pinyin: 'shuǐ guǒ', tones: [3, 3], meaning: 'fruit', deck: 'Nouns · Food' },
  { simplified: '汤', traditional: '湯', pinyin: 'tāng', tones: [1], meaning: 'soup', deck: 'Nouns · Food' },

  // ── Nouns · Drinks ───────────────────────────────────────
  { simplified: '水', traditional: '水', pinyin: 'shuǐ', tones: [3], meaning: 'water', deck: 'Nouns · Drinks' },
  { simplified: '茶', traditional: '茶', pinyin: 'chá', tones: [2], meaning: 'tea', deck: 'Nouns · Drinks' },
  { simplified: '咖啡', traditional: '咖啡', pinyin: 'kā fēi', tones: [1, 1], meaning: 'coffee', deck: 'Nouns · Drinks' },
  { simplified: '牛奶', traditional: '牛奶', pinyin: 'niú nǎi', tones: [2, 3], meaning: 'milk', deck: 'Nouns · Drinks' },
  { simplified: '果汁', traditional: '果汁', pinyin: 'guǒ zhī', tones: [3, 1], meaning: 'fruit juice', deck: 'Nouns · Drinks' },
  { simplified: '啤酒', traditional: '啤酒', pinyin: 'pí jiǔ', tones: [2, 3], meaning: 'beer', deck: 'Nouns · Drinks' },
  { simplified: '矿泉水', traditional: '礦泉水', pinyin: 'kuàng quán shuǐ', tones: [4, 2, 3], meaning: 'mineral water', deck: 'Nouns · Drinks' },

  // ── Places ───────────────────────────────────────────────
  { simplified: '中国', traditional: '中國', pinyin: 'zhōng guó', tones: [1, 2], meaning: 'China', deck: 'Places' },
  { simplified: '北京', traditional: '北京', pinyin: 'běi jīng', tones: [3, 1], meaning: 'Beijing', deck: 'Places' },
  { simplified: '学校', traditional: '學校', pinyin: 'xué xiào', tones: [2, 4], meaning: 'school', deck: 'Places' },
  { simplified: '医院', traditional: '醫院', pinyin: 'yī yuàn', tones: [1, 4], meaning: 'hospital', deck: 'Places' },
  { simplified: '商店', traditional: '商店', pinyin: 'shāng diàn', tones: [1, 4], meaning: 'shop / store', deck: 'Places' },
  { simplified: '超市', traditional: '超市', pinyin: 'chāo shì', tones: [1, 4], meaning: 'supermarket', deck: 'Places' },
  { simplified: '银行', traditional: '銀行', pinyin: 'yín háng', tones: [2, 2], meaning: 'bank', deck: 'Places' },
  { simplified: '饭店', traditional: '飯店', pinyin: 'fàn diàn', tones: [4, 4], meaning: 'restaurant / hotel', deck: 'Places' },
  { simplified: '图书馆', traditional: '圖書館', pinyin: 'tú shū guǎn', tones: [2, 1, 3], meaning: 'library', deck: 'Places' },
  { simplified: '教室', traditional: '教室', pinyin: 'jiào shì', tones: [4, 4], meaning: 'classroom', deck: 'Places' },
  { simplified: '机场', traditional: '機場', pinyin: 'jī chǎng', tones: [1, 3], meaning: 'airport', deck: 'Places' },
  { simplified: '火车站', traditional: '火車站', pinyin: 'huǒ chē zhàn', tones: [3, 1, 4], meaning: 'train station', deck: 'Places' },
  { simplified: '公园', traditional: '公園', pinyin: 'gōng yuán', tones: [1, 2], meaning: 'park', deck: 'Places' },
  { simplified: '邮局', traditional: '郵局', pinyin: 'yóu jú', tones: [2, 2], meaning: 'post office', deck: 'Places' },
  { simplified: '厕所', traditional: '廁所', pinyin: 'cè suǒ', tones: [4, 3], meaning: 'toilet / bathroom', deck: 'Places' },
  { simplified: '房间', traditional: '房間', pinyin: 'fáng jiān', tones: [2, 1], meaning: 'room', deck: 'Places' },

  // ── Transportation ───────────────────────────────────────
  { simplified: '出租车', traditional: '出租車', pinyin: 'chū zū chē', tones: [1, 1, 1], meaning: 'taxi', deck: 'Transportation' },
  { simplified: '火车', traditional: '火車', pinyin: 'huǒ chē', tones: [3, 1], meaning: 'train', deck: 'Transportation' },
  { simplified: '飞机', traditional: '飛機', pinyin: 'fēi jī', tones: [1, 1], meaning: 'airplane', deck: 'Transportation' },
  { simplified: '汽车', traditional: '汽車', pinyin: 'qì chē', tones: [4, 1], meaning: 'car', deck: 'Transportation' },
  { simplified: '地铁', traditional: '地鐵', pinyin: 'dì tiě', tones: [4, 3], meaning: 'subway', deck: 'Transportation' },
  { simplified: '自行车', traditional: '自行車', pinyin: 'zì xíng chē', tones: [4, 2, 1], meaning: 'bicycle', deck: 'Transportation' },
  { simplified: '公共汽车', traditional: '公共汽車', pinyin: 'gōng gòng qì chē', tones: [1, 4, 4, 1], meaning: 'bus', deck: 'Transportation' },
  { simplified: '路', traditional: '路', pinyin: 'lù', tones: [4], meaning: 'road / route', deck: 'Transportation' },

  // ── Colors ───────────────────────────────────────────────
  { simplified: '颜色', traditional: '顏色', pinyin: 'yán sè', tones: [2, 4], meaning: 'color', deck: 'Colors' },
  { simplified: '红色', traditional: '紅色', pinyin: 'hóng sè', tones: [2, 4], meaning: 'red', deck: 'Colors' },
  { simplified: '白色', traditional: '白色', pinyin: 'bái sè', tones: [2, 4], meaning: 'white', deck: 'Colors' },
  { simplified: '黑色', traditional: '黑色', pinyin: 'hēi sè', tones: [1, 4], meaning: 'black', deck: 'Colors' },
  { simplified: '黄色', traditional: '黃色', pinyin: 'huáng sè', tones: [2, 4], meaning: 'yellow', deck: 'Colors' },
  { simplified: '绿色', traditional: '綠色', pinyin: 'lǜ sè', tones: [4, 4], meaning: 'green', deck: 'Colors' },
  { simplified: '蓝色', traditional: '藍色', pinyin: 'lán sè', tones: [2, 4], meaning: 'blue', deck: 'Colors' },

  // ── Clothing ─────────────────────────────────────────────
  { simplified: '衣服', traditional: '衣服', pinyin: 'yī fu', tones: [1, 0], meaning: 'clothes', deck: 'Clothing' },
  { simplified: '裤子', traditional: '褲子', pinyin: 'kù zi', tones: [4, 0], meaning: 'pants / trousers', deck: 'Clothing' },
  { simplified: '鞋子', traditional: '鞋子', pinyin: 'xié zi', tones: [2, 0], meaning: 'shoes', deck: 'Clothing' },
  { simplified: '裙子', traditional: '裙子', pinyin: 'qún zi', tones: [2, 0], meaning: 'skirt', deck: 'Clothing' },
  { simplified: '帽子', traditional: '帽子', pinyin: 'mào zi', tones: [4, 0], meaning: 'hat', deck: 'Clothing' },
  { simplified: '袜子', traditional: '襪子', pinyin: 'wà zi', tones: [4, 0], meaning: 'socks', deck: 'Clothing' },
  { simplified: '衬衫', traditional: '襯衫', pinyin: 'chèn shān', tones: [4, 1], meaning: 'shirt', deck: 'Clothing' },

  // ── Body & Health ────────────────────────────────────────
  { simplified: '身体', traditional: '身體', pinyin: 'shēn tǐ', tones: [1, 3], meaning: 'body', deck: 'Body & Health' },
  { simplified: '头', traditional: '頭', pinyin: 'tóu', tones: [2], meaning: 'head', deck: 'Body & Health' },
  { simplified: '眼睛', traditional: '眼睛', pinyin: 'yǎn jīng', tones: [3, 1], meaning: 'eyes', deck: 'Body & Health' },
  { simplified: '耳朵', traditional: '耳朵', pinyin: 'ěr duǒ', tones: [3, 0], meaning: 'ears', deck: 'Body & Health' },
  { simplified: '鼻子', traditional: '鼻子', pinyin: 'bí zi', tones: [2, 0], meaning: 'nose', deck: 'Body & Health' },
  { simplified: '嘴', traditional: '嘴', pinyin: 'zuǐ', tones: [3], meaning: 'mouth', deck: 'Body & Health' },
  { simplified: '手', traditional: '手', pinyin: 'shǒu', tones: [3], meaning: 'hand', deck: 'Body & Health' },
  { simplified: '脚', traditional: '腳', pinyin: 'jiǎo', tones: [3], meaning: 'foot', deck: 'Body & Health' },
  { simplified: '脸', traditional: '臉', pinyin: 'liǎn', tones: [3], meaning: 'face', deck: 'Body & Health' },
  { simplified: '头疼', traditional: '頭疼', pinyin: 'tóu téng', tones: [2, 2], meaning: 'headache', deck: 'Body & Health' },
  { simplified: '发烧', traditional: '發燒', pinyin: 'fā shāo', tones: [1, 1], meaning: 'fever', deck: 'Body & Health' },
  { simplified: '药', traditional: '藥', pinyin: 'yào', tones: [4], meaning: 'medicine', deck: 'Body & Health' },

  // ── Weather & Nature ─────────────────────────────────────
  { simplified: '天气', traditional: '天氣', pinyin: 'tiān qì', tones: [1, 4], meaning: 'weather', deck: 'Weather & Nature' },
  { simplified: '太阳', traditional: '太陽', pinyin: 'tài yáng', tones: [4, 2], meaning: 'sun', deck: 'Weather & Nature' },
  { simplified: '云', traditional: '雲', pinyin: 'yún', tones: [2], meaning: 'cloud', deck: 'Weather & Nature' },
  { simplified: '风', traditional: '風', pinyin: 'fēng', tones: [1], meaning: 'wind', deck: 'Weather & Nature' },
  { simplified: '下雨', traditional: '下雨', pinyin: 'xià yǔ', tones: [4, 3], meaning: 'to rain', deck: 'Weather & Nature' },
  { simplified: '下雪', traditional: '下雪', pinyin: 'xià xuě', tones: [4, 3], meaning: 'to snow', deck: 'Weather & Nature' },
  { simplified: '热', traditional: '熱', pinyin: 'rè', tones: [4], meaning: 'hot', deck: 'Weather & Nature' },
  { simplified: '冷', traditional: '冷', pinyin: 'lěng', tones: [3], meaning: 'cold', deck: 'Weather & Nature' },

  // ── Home & Objects ───────────────────────────────────────
  { simplified: '房子', traditional: '房子', pinyin: 'fáng zi', tones: [2, 0], meaning: 'house', deck: 'Home & Objects' },
  { simplified: '门', traditional: '門', pinyin: 'mén', tones: [2], meaning: 'door', deck: 'Home & Objects' },
  { simplified: '窗户', traditional: '窗戶', pinyin: 'chuāng hu', tones: [1, 0], meaning: 'window', deck: 'Home & Objects' },
  { simplified: '床', traditional: '床', pinyin: 'chuáng', tones: [2], meaning: 'bed', deck: 'Home & Objects' },
  { simplified: '桌子', traditional: '桌子', pinyin: 'zhuō zi', tones: [1, 0], meaning: 'table / desk', deck: 'Home & Objects' },
  { simplified: '椅子', traditional: '椅子', pinyin: 'yǐ zi', tones: [3, 0], meaning: 'chair', deck: 'Home & Objects' },
  { simplified: '电视', traditional: '電視', pinyin: 'diàn shì', tones: [4, 4], meaning: 'TV / television', deck: 'Home & Objects' },
  { simplified: '电脑', traditional: '電腦', pinyin: 'diàn nǎo', tones: [4, 3], meaning: 'computer', deck: 'Home & Objects' },
  { simplified: '手机', traditional: '手機', pinyin: 'shǒu jī', tones: [3, 1], meaning: 'mobile phone', deck: 'Home & Objects' },
  { simplified: '电话', traditional: '電話', pinyin: 'diàn huà', tones: [4, 4], meaning: 'telephone', deck: 'Home & Objects' },
  { simplified: '照片', traditional: '照片', pinyin: 'zhào piàn', tones: [4, 4], meaning: 'photo', deck: 'Home & Objects' },

  // ── School ───────────────────────────────────────────────
  { simplified: '书', traditional: '書', pinyin: 'shū', tones: [1], meaning: 'book', deck: 'School' },
  { simplified: '汉语', traditional: '漢語', pinyin: 'hàn yǔ', tones: [4, 3], meaning: 'Chinese language', deck: 'School' },
  { simplified: '汉字', traditional: '漢字', pinyin: 'hàn zì', tones: [4, 4], meaning: 'Chinese character', deck: 'School' },
  { simplified: '课', traditional: '課', pinyin: 'kè', tones: [4], meaning: 'lesson / class', deck: 'School' },
  { simplified: '作业', traditional: '作業', pinyin: 'zuò yè', tones: [4, 4], meaning: 'homework', deck: 'School' },
  { simplified: '考试', traditional: '考試', pinyin: 'kǎo shì', tones: [3, 4], meaning: 'exam', deck: 'School' },
  { simplified: '字', traditional: '字', pinyin: 'zì', tones: [4], meaning: 'character / word', deck: 'School' },
  { simplified: '问题', traditional: '問題', pinyin: 'wèn tí', tones: [4, 2], meaning: 'question / problem', deck: 'School' },
  { simplified: '学习', traditional: '學習', pinyin: 'xué xí', tones: [2, 2], meaning: 'to study / learn', deck: 'School' },

  // ── Work & Shopping ──────────────────────────────────────
  { simplified: '工作', traditional: '工作', pinyin: 'gōng zuò', tones: [1, 4], meaning: 'work / job', deck: 'Work & Shopping' },
  { simplified: '公司', traditional: '公司', pinyin: 'gōng sī', tones: [1, 1], meaning: 'company', deck: 'Work & Shopping' },
  { simplified: '钱', traditional: '錢', pinyin: 'qián', tones: [2], meaning: 'money', deck: 'Work & Shopping' },
  { simplified: '块', traditional: '塊', pinyin: 'kuài', tones: [4], meaning: 'yuan (colloquial) / piece', deck: 'Work & Shopping' },
  { simplified: '元', traditional: '元', pinyin: 'yuán', tones: [2], meaning: 'yuan (formal)', deck: 'Work & Shopping' },
  { simplified: '多少钱', traditional: '多少錢', pinyin: 'duō shao qián', tones: [1, 0, 2], meaning: 'how much money', deck: 'Work & Shopping' },

  // ── Verbs · Core ─────────────────────────────────────────
  { simplified: '是', traditional: '是', pinyin: 'shì', tones: [4], meaning: 'to be', deck: 'Verbs · Core' },
  { simplified: '有', traditional: '有', pinyin: 'yǒu', tones: [3], meaning: 'to have', deck: 'Verbs · Core' },
  { simplified: '在', traditional: '在', pinyin: 'zài', tones: [4], meaning: 'to be at / in', deck: 'Verbs · Core' },
  { simplified: '去', traditional: '去', pinyin: 'qù', tones: [4], meaning: 'to go', deck: 'Verbs · Core' },
  { simplified: '来', traditional: '來', pinyin: 'lái', tones: [2], meaning: 'to come', deck: 'Verbs · Core' },
  { simplified: '说', traditional: '說', pinyin: 'shuō', tones: [1], meaning: 'to speak / say', deck: 'Verbs · Core' },
  { simplified: '看', traditional: '看', pinyin: 'kàn', tones: [4], meaning: 'to look / watch', deck: 'Verbs · Core' },
  { simplified: '听', traditional: '聽', pinyin: 'tīng', tones: [1], meaning: 'to listen', deck: 'Verbs · Core' },
  { simplified: '吃', traditional: '吃', pinyin: 'chī', tones: [1], meaning: 'to eat', deck: 'Verbs · Core' },
  { simplified: '喝', traditional: '喝', pinyin: 'hē', tones: [1], meaning: 'to drink', deck: 'Verbs · Core' },
  { simplified: '买', traditional: '買', pinyin: 'mǎi', tones: [3], meaning: 'to buy', deck: 'Verbs · Core' },
  { simplified: '卖', traditional: '賣', pinyin: 'mài', tones: [4], meaning: 'to sell', deck: 'Verbs · Core' },
  { simplified: '做', traditional: '做', pinyin: 'zuò', tones: [4], meaning: 'to do / make', deck: 'Verbs · Core' },
  { simplified: '知道', traditional: '知道', pinyin: 'zhī dào', tones: [1, 4], meaning: 'to know (a fact)', deck: 'Verbs · Core' },
  { simplified: '认识', traditional: '認識', pinyin: 'rèn shi', tones: [4, 0], meaning: 'to know (a person)', deck: 'Verbs · Core' },
  { simplified: '喜欢', traditional: '喜歡', pinyin: 'xǐ huan', tones: [3, 0], meaning: 'to like', deck: 'Verbs · Core' },
  { simplified: '爱', traditional: '愛', pinyin: 'ài', tones: [4], meaning: 'to love', deck: 'Verbs · Core' },
  { simplified: '想', traditional: '想', pinyin: 'xiǎng', tones: [3], meaning: 'to think / want', deck: 'Verbs · Core' },
  { simplified: '要', traditional: '要', pinyin: 'yào', tones: [4], meaning: 'to want / need', deck: 'Verbs · Core' },
  { simplified: '可以', traditional: '可以', pinyin: 'kě yǐ', tones: [3, 3], meaning: 'can / may', deck: 'Verbs · Core' },
  { simplified: '能', traditional: '能', pinyin: 'néng', tones: [2], meaning: 'can / be able to', deck: 'Verbs · Core' },
  { simplified: '会', traditional: '會', pinyin: 'huì', tones: [4], meaning: 'can / know how to', deck: 'Verbs · Core' },

  // ── Verbs · Daily Life ───────────────────────────────────
  { simplified: '住', traditional: '住', pinyin: 'zhù', tones: [4], meaning: 'to live / reside', deck: 'Verbs · Daily Life' },
  { simplified: '等', traditional: '等', pinyin: 'děng', tones: [3], meaning: 'to wait', deck: 'Verbs · Daily Life' },
  { simplified: '走', traditional: '走', pinyin: 'zǒu', tones: [3], meaning: 'to walk / go', deck: 'Verbs · Daily Life' },
  { simplified: '坐', traditional: '坐', pinyin: 'zuò', tones: [4], meaning: 'to sit / travel by', deck: 'Verbs · Daily Life' },
  { simplified: '站', traditional: '站', pinyin: 'zhàn', tones: [4], meaning: 'to stand', deck: 'Verbs · Daily Life' },
  { simplified: '问', traditional: '問', pinyin: 'wèn', tones: [4], meaning: 'to ask', deck: 'Verbs · Daily Life' },
  { simplified: '叫', traditional: '叫', pinyin: 'jiào', tones: [4], meaning: 'to be called / to call', deck: 'Verbs · Daily Life' },
  { simplified: '给', traditional: '給', pinyin: 'gěi', tones: [3], meaning: 'to give', deck: 'Verbs · Daily Life' },
  { simplified: '回', traditional: '回', pinyin: 'huí', tones: [2], meaning: 'to return', deck: 'Verbs · Daily Life' },
  { simplified: '进', traditional: '進', pinyin: 'jìn', tones: [4], meaning: 'to enter', deck: 'Verbs · Daily Life' },
  { simplified: '出', traditional: '出', pinyin: 'chū', tones: [1], meaning: 'to go out / exit', deck: 'Verbs · Daily Life' },
  { simplified: '睡觉', traditional: '睡覺', pinyin: 'shuì jiào', tones: [4, 4], meaning: 'to sleep', deck: 'Verbs · Daily Life' },
  { simplified: '起床', traditional: '起床', pinyin: 'qǐ chuáng', tones: [3, 2], meaning: 'to get up', deck: 'Verbs · Daily Life' },
  { simplified: '洗', traditional: '洗', pinyin: 'xǐ', tones: [3], meaning: 'to wash', deck: 'Verbs · Daily Life' },
  { simplified: '穿', traditional: '穿', pinyin: 'chuān', tones: [1], meaning: 'to wear', deck: 'Verbs · Daily Life' },
  { simplified: '用', traditional: '用', pinyin: 'yòng', tones: [4], meaning: 'to use', deck: 'Verbs · Daily Life' },
  { simplified: '找', traditional: '找', pinyin: 'zhǎo', tones: [3], meaning: 'to look for', deck: 'Verbs · Daily Life' },
  { simplified: '觉得', traditional: '覺得', pinyin: 'jué de', tones: [2, 0], meaning: 'to feel / think', deck: 'Verbs · Daily Life' },
  { simplified: '看见', traditional: '看見', pinyin: 'kàn jiàn', tones: [4, 4], meaning: 'to see', deck: 'Verbs · Daily Life' },
  { simplified: '告诉', traditional: '告訴', pinyin: 'gào su', tones: [4, 0], meaning: 'to tell', deck: 'Verbs · Daily Life' },
  { simplified: '帮助', traditional: '幫助', pinyin: 'bāng zhù', tones: [1, 4], meaning: 'to help', deck: 'Verbs · Daily Life' },
  { simplified: '开始', traditional: '開始', pinyin: 'kāi shǐ', tones: [1, 3], meaning: 'to start', deck: 'Verbs · Daily Life' },
  { simplified: '休息', traditional: '休息', pinyin: 'xiū xi', tones: [1, 0], meaning: 'to rest', deck: 'Verbs · Daily Life' },
  { simplified: '打电话', traditional: '打電話', pinyin: 'dǎ diàn huà', tones: [3, 4, 4], meaning: 'to make a phone call', deck: 'Verbs · Daily Life' },
  { simplified: '写', traditional: '寫', pinyin: 'xiě', tones: [3], meaning: 'to write', deck: 'Verbs · Daily Life' },
  { simplified: '读', traditional: '讀', pinyin: 'dú', tones: [2], meaning: 'to read (aloud)', deck: 'Verbs · Daily Life' },
  { simplified: '开', traditional: '開', pinyin: 'kāi', tones: [1], meaning: 'to open / drive', deck: 'Verbs · Daily Life' },
  { simplified: '关', traditional: '關', pinyin: 'guān', tones: [1], meaning: 'to close', deck: 'Verbs · Daily Life' },

  // ── Verbs · Activities ───────────────────────────────────
  { simplified: '玩', traditional: '玩', pinyin: 'wán', tones: [2], meaning: 'to play', deck: 'Verbs · Activities' },
  { simplified: '跑步', traditional: '跑步', pinyin: 'pǎo bù', tones: [3, 4], meaning: 'to run / jog', deck: 'Verbs · Activities' },
  { simplified: '游泳', traditional: '游泳', pinyin: 'yóu yǒng', tones: [2, 3], meaning: 'to swim', deck: 'Verbs · Activities' },
  { simplified: '唱歌', traditional: '唱歌', pinyin: 'chàng gē', tones: [4, 1], meaning: 'to sing', deck: 'Verbs · Activities' },
  { simplified: '跳舞', traditional: '跳舞', pinyin: 'tiào wǔ', tones: [4, 3], meaning: 'to dance', deck: 'Verbs · Activities' },
  { simplified: '踢足球', traditional: '踢足球', pinyin: 'tī zú qiú', tones: [1, 2, 2], meaning: 'to play football / soccer', deck: 'Verbs · Activities' },
  { simplified: '打篮球', traditional: '打籃球', pinyin: 'dǎ lán qiú', tones: [3, 2, 2], meaning: 'to play basketball', deck: 'Verbs · Activities' },
  { simplified: '看书', traditional: '看書', pinyin: 'kàn shū', tones: [4, 1], meaning: 'to read a book', deck: 'Verbs · Activities' },
  { simplified: '看电影', traditional: '看電影', pinyin: 'kàn diàn yǐng', tones: [4, 4, 3], meaning: 'to watch a movie', deck: 'Verbs · Activities' },
  { simplified: '听音乐', traditional: '聽音樂', pinyin: 'tīng yīn yuè', tones: [1, 1, 4], meaning: 'to listen to music', deck: 'Verbs · Activities' },
  { simplified: '旅游', traditional: '旅遊', pinyin: 'lǚ yóu', tones: [3, 2], meaning: 'to travel', deck: 'Verbs · Activities' },
  { simplified: '爬山', traditional: '爬山', pinyin: 'pá shān', tones: [2, 1], meaning: 'to hike / climb a mountain', deck: 'Verbs · Activities' },

  // ── Adjectives ───────────────────────────────────────────
  { simplified: '好', traditional: '好', pinyin: 'hǎo', tones: [3], meaning: 'good', deck: 'Adjectives' },
  { simplified: '大', traditional: '大', pinyin: 'dà', tones: [4], meaning: 'big / large', deck: 'Adjectives' },
  { simplified: '小', traditional: '小', pinyin: 'xiǎo', tones: [3], meaning: 'small / little', deck: 'Adjectives' },
  { simplified: '多', traditional: '多', pinyin: 'duō', tones: [1], meaning: 'many / much', deck: 'Adjectives' },
  { simplified: '少', traditional: '少', pinyin: 'shǎo', tones: [3], meaning: 'few / little', deck: 'Adjectives' },
  { simplified: '高', traditional: '高', pinyin: 'gāo', tones: [1], meaning: 'tall / high', deck: 'Adjectives' },
  { simplified: '矮', traditional: '矮', pinyin: 'ǎi', tones: [3], meaning: 'short (height)', deck: 'Adjectives' },
  { simplified: '长', traditional: '長', pinyin: 'cháng', tones: [2], meaning: 'long', deck: 'Adjectives' },
  { simplified: '短', traditional: '短', pinyin: 'duǎn', tones: [3], meaning: 'short (length)', deck: 'Adjectives' },
  { simplified: '胖', traditional: '胖', pinyin: 'pàng', tones: [4], meaning: 'fat / chubby', deck: 'Adjectives' },
  { simplified: '瘦', traditional: '瘦', pinyin: 'shòu', tones: [4], meaning: 'thin / slim', deck: 'Adjectives' },
  { simplified: '漂亮', traditional: '漂亮', pinyin: 'piào liang', tones: [4, 0], meaning: 'beautiful / pretty', deck: 'Adjectives' },
  { simplified: '帅', traditional: '帥', pinyin: 'shuài', tones: [4], meaning: 'handsome', deck: 'Adjectives' },
  { simplified: '好看', traditional: '好看', pinyin: 'hǎo kàn', tones: [3, 4], meaning: 'good-looking', deck: 'Adjectives' },
  { simplified: '新', traditional: '新', pinyin: 'xīn', tones: [1], meaning: 'new', deck: 'Adjectives' },
  { simplified: '旧', traditional: '舊', pinyin: 'jiù', tones: [4], meaning: 'old / used', deck: 'Adjectives' },
  { simplified: '贵', traditional: '貴', pinyin: 'guì', tones: [4], meaning: 'expensive', deck: 'Adjectives' },
  { simplified: '便宜', traditional: '便宜', pinyin: 'pián yi', tones: [2, 0], meaning: 'cheap / inexpensive', deck: 'Adjectives' },
  { simplified: '快', traditional: '快', pinyin: 'kuài', tones: [4], meaning: 'fast / quick', deck: 'Adjectives' },
  { simplified: '慢', traditional: '慢', pinyin: 'màn', tones: [4], meaning: 'slow', deck: 'Adjectives' },
  { simplified: '远', traditional: '遠', pinyin: 'yuǎn', tones: [3], meaning: 'far', deck: 'Adjectives' },
  { simplified: '近', traditional: '近', pinyin: 'jìn', tones: [4], meaning: 'near / close', deck: 'Adjectives' },
  { simplified: '难', traditional: '難', pinyin: 'nán', tones: [2], meaning: 'difficult', deck: 'Adjectives' },
  { simplified: '容易', traditional: '容易', pinyin: 'róng yì', tones: [2, 4], meaning: 'easy', deck: 'Adjectives' },
  { simplified: '累', traditional: '累', pinyin: 'lèi', tones: [4], meaning: 'tired', deck: 'Adjectives' },
  { simplified: '忙', traditional: '忙', pinyin: 'máng', tones: [2], meaning: 'busy', deck: 'Adjectives' },
  { simplified: '高兴', traditional: '高興', pinyin: 'gāo xìng', tones: [1, 4], meaning: 'happy / glad', deck: 'Adjectives' },
  { simplified: '开心', traditional: '開心', pinyin: 'kāi xīn', tones: [1, 1], meaning: 'happy / joyful', deck: 'Adjectives' },
  { simplified: '难过', traditional: '難過', pinyin: 'nán guò', tones: [2, 4], meaning: 'sad / upset', deck: 'Adjectives' },
  { simplified: '健康', traditional: '健康', pinyin: 'jiàn kāng', tones: [4, 1], meaning: 'healthy', deck: 'Adjectives' },
  { simplified: '对', traditional: '對', pinyin: 'duì', tones: [4], meaning: 'correct / right', deck: 'Adjectives' },
  { simplified: '错', traditional: '錯', pinyin: 'cuò', tones: [4], meaning: 'wrong', deck: 'Adjectives' },
  { simplified: '方便', traditional: '方便', pinyin: 'fāng biàn', tones: [1, 4], meaning: 'convenient', deck: 'Adjectives' },
  { simplified: '干净', traditional: '乾淨', pinyin: 'gān jìng', tones: [1, 4], meaning: 'clean', deck: 'Adjectives' },
  { simplified: '暖和', traditional: '暖和', pinyin: 'nuǎn huo', tones: [3, 0], meaning: 'warm', deck: 'Adjectives' },
  { simplified: '凉快', traditional: '涼快', pinyin: 'liáng kuài', tones: [2, 4], meaning: 'pleasantly cool', deck: 'Adjectives' },

  // ── Adverbs & Particles ──────────────────────────────────
  { simplified: '不', traditional: '不', pinyin: 'bù', tones: [4], meaning: 'not / no', deck: 'Adverbs & Particles' },
  { simplified: '没有', traditional: '沒有', pinyin: 'méi yǒu', tones: [2, 3], meaning: "don't have / there isn't", deck: 'Adverbs & Particles' },
  { simplified: '也', traditional: '也', pinyin: 'yě', tones: [3], meaning: 'also / too', deck: 'Adverbs & Particles' },
  { simplified: '都', traditional: '都', pinyin: 'dōu', tones: [1], meaning: 'all / both', deck: 'Adverbs & Particles' },
  { simplified: '很', traditional: '很', pinyin: 'hěn', tones: [3], meaning: 'very', deck: 'Adverbs & Particles' },
  { simplified: '非常', traditional: '非常', pinyin: 'fēi cháng', tones: [1, 2], meaning: 'extremely', deck: 'Adverbs & Particles' },
  { simplified: '太', traditional: '太', pinyin: 'tài', tones: [4], meaning: 'too / excessively', deck: 'Adverbs & Particles' },
  { simplified: '只', traditional: '只', pinyin: 'zhǐ', tones: [3], meaning: 'only', deck: 'Adverbs & Particles' },
  { simplified: '就', traditional: '就', pinyin: 'jiù', tones: [4], meaning: 'just / then', deck: 'Adverbs & Particles' },
  { simplified: '还', traditional: '還', pinyin: 'hái', tones: [2], meaning: 'still / also', deck: 'Adverbs & Particles' },
  { simplified: '又', traditional: '又', pinyin: 'yòu', tones: [4], meaning: 'again (past)', deck: 'Adverbs & Particles' },
  { simplified: '再', traditional: '再', pinyin: 'zài', tones: [4], meaning: 'again (future)', deck: 'Adverbs & Particles' },
  { simplified: '已经', traditional: '已經', pinyin: 'yǐ jīng', tones: [3, 1], meaning: 'already', deck: 'Adverbs & Particles' },
  { simplified: '因为', traditional: '因為', pinyin: 'yīn wèi', tones: [1, 4], meaning: 'because', deck: 'Adverbs & Particles' },
  { simplified: '所以', traditional: '所以', pinyin: 'suǒ yǐ', tones: [3, 3], meaning: 'therefore / so', deck: 'Adverbs & Particles' },
  { simplified: '但是', traditional: '但是', pinyin: 'dàn shì', tones: [4, 4], meaning: 'but / however', deck: 'Adverbs & Particles' },
  { simplified: '和', traditional: '和', pinyin: 'hé', tones: [2], meaning: 'and / with', deck: 'Adverbs & Particles' },
  { simplified: '跟', traditional: '跟', pinyin: 'gēn', tones: [1], meaning: 'with / follow', deck: 'Adverbs & Particles' },
  { simplified: '的', traditional: '的', pinyin: 'de', tones: [0], meaning: '(possessive / descriptive particle)', deck: 'Adverbs & Particles' },
  { simplified: '了', traditional: '了', pinyin: 'le', tones: [0], meaning: '(completion / change particle)', deck: 'Adverbs & Particles' },
  { simplified: '吗', traditional: '嗎', pinyin: 'ma', tones: [0], meaning: '(yes/no question particle)', deck: 'Adverbs & Particles' },
  { simplified: '呢', traditional: '呢', pinyin: 'ne', tones: [0], meaning: '(continuation question particle)', deck: 'Adverbs & Particles' },
  { simplified: '吧', traditional: '吧', pinyin: 'ba', tones: [0], meaning: '(suggestion / confirmation particle)', deck: 'Adverbs & Particles' },
  { simplified: '还是', traditional: '還是', pinyin: 'hái shì', tones: [2, 4], meaning: 'or (in questions)', deck: 'Adverbs & Particles' },
  { simplified: '或者', traditional: '或者', pinyin: 'huò zhě', tones: [4, 3], meaning: 'or (in statements)', deck: 'Adverbs & Particles' },
  { simplified: '如果', traditional: '如果', pinyin: 'rú guǒ', tones: [2, 3], meaning: 'if', deck: 'Adverbs & Particles' },
]

async function seed() {
  console.log('Seeding database…')

  // Upsert decks
  const insertedDecks = await db
    .insert(decks)
    .values(HSK1_DECKS)
    .onConflictDoUpdate({ target: decks.name, set: { description: decks.description } })
    .returning({ id: decks.id, name: decks.name })

  const deckMap = Object.fromEntries(insertedDecks.map((d) => [d.name, d.id]))

  // Deduplicate by simplified form before inserting
  const seen = new Set<string>()
  const wordRows = HSK1_WORDS
    .filter((w) => {
      if (seen.has(w.simplified)) return false
      seen.add(w.simplified)
      return true
    })
    .map((w) => ({
      simplified: w.simplified,
      traditional: w.traditional,
      pinyin: w.pinyin,
      tones: w.tones,
      meaning: w.meaning,
      deckId: deckMap[w.deck],
    }))

  await db
    .insert(words)
    .values(wordRows)
    .onConflictDoNothing()

  console.log(`Seeded ${insertedDecks.length} decks and ${wordRows.length} words.`)
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
})
